openapi: 3.0.0
info:
  title: Healthcare API
  version: 1.0.0
  description: API para gestionar doctores, pacientes y citas médicas.
paths:
  /api/doctors:
    get:
      summary: Obtiene todos los doctores registrados
      responses:
        '200':
          description: Lista de doctores
          content:
            application/json:
              schema:
                type: object
                properties:
                  responseStatus:
                    type: string
                  details:
                    type: string
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id: { type: string }
                        name: { type: string }
                        surname: { type: string }
                        speciality: { type: string }
                        email: { type: string }
                        phone: { type: string }

  /api/doctors/speciality/{speciality}:
    get:
      summary: Obtiene doctores filtrados por especialidad
      parameters:
        - name: speciality
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Doctores filtrados por especialidad
          content:
            application/json:
              schema:
                type: object
                properties:
                  responseStatus: { type: string }
                  details: { type: string }
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id: { type: string }
                        name: { type: string }
                        surname: { type: string }
                        speciality: { type: string }
                        email: { type: string }
                        phone: { type: string }

  /api/doctors/id/{doctorId}:
    get:
      summary: Obtiene un doctor por su ID
      parameters:
        - name: doctorId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Datos del doctor
          content:
            application/json:
              schema:
                type: object
                properties:
                  responseStatus: { type: string }
                  details: { type: string }
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id: { type: string }
                        name: { type: string }
                        surname: { type: string }
                        speciality: { type: string }
                        email: { type: string }
                        phone: { type: string }

  /api/doctors/fullName/{name}/{surname}:
    get:
      summary: Obtiene doctores por nombre y apellido
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: string
        - name: surname
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Doctores encontrados por nombre y apellido
          content:
            application/json:
              schema:
                type: object
                properties:
                  responseStatus: { type: string }
                  details: { type: string }
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id: { type: string }
                        name: { type: string }
                        surname: { type: string }
                        speciality: { type: string }
                        email: { type: string }
                        phone: { type: string }

  /api/doctors/create:
    post:
      summary: Crea un nuevo doctor
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name: { type: string }
                surname: { type: string }
                speciality: { type: string }
                email: { type: string }
                phone: { type: string }
      responses:
        '200':
          description: Resultado de la creación del doctor
          content:
            application/json:
              schema:
                type: object
                properties:
                  responseStatus: { type: string }
                  details: { type: string }
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id: { type: string }

  /api/doctors/remove/{doctorId}:
    put:
      summary: Elimina (o desactiva) un doctor por su ID
      parameters:
        - name: doctorId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Resultado de la eliminación del doctor
          content:
            application/json:
              schema:
                type: object
                properties:
                  responseStatus: { type: string }
                  details: { type: string }
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id: { type: string }
